#!/bin/bash

set -eo pipefail

function start {
  docker compose up --build -d "${@}"
}

function mongo {
  docker exec -it uwazi-mongo mongo localhost/uwazi_development
}

function stop {
  docker compose stop
}

# I would create the following functions:
# - backup: to create a backup of the all the data needed
# - restore: to restore the data from a backup
# - initialize: to initialize the database
# - serve: to start the application

function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
